"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-10-03 10:10:32.573195
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

import clipper.db.types


revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'entity_id', name='uq_discord_ref')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ts', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('handled_by_session', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_type_ts', ['type', 'ts'], unique=False)

    op.create_table('kv',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('lease',
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('holder_session', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('resource')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_scope'), ['scope'], unique=False)

    op.create_table('marketplace',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_ok', sa.Boolean(), nullable=False),
    sa.Column('last_scout', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('acked_by_session', sa.Integer(), nullable=True),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_scope_id'), ['scope_id'], unique=False)

    op.create_table('platform',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_window',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('resets_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('rate_limited', sa.Boolean(), nullable=False),
    sa.Column('utilization', sa.Float(), nullable=False),
    sa.Column('window_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chrome_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('niche_tags', sa.JSON(), nullable=False),
    sa.Column('warmup_started', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('daily_cap', sa.Integer(), nullable=True),
    sa.Column('min_gap_min', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paused_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_platform'), ['platform'], unique=False)

    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=False),
    sa.Column('budget_total', sa.Float(), nullable=True),
    sa.Column('budget_left', sa.Float(), nullable=True),
    sa.Column('cap_per_clip', sa.Float(), nullable=True),
    sa.Column('min_views_to_pay', sa.Integer(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('deliverable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tracking_window_days', sa.Integer(), nullable=True),
    sa.Column('deadline', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('rules_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('agent_turns', sa.Integer(), nullable=False),
    sa.Column('budget_runs_out_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('found_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('taken_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('updated_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['marketplace'], ['marketplace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'external_id', name='uq_campaign_market_ext')
    )
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_creator'), ['creator'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_marketplace'), ['marketplace'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_status'), ['status'], unique=False)

    op.create_table('agent_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('merged_count', sa.Integer(), nullable=False),
    sa.Column('queued_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('started_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('finished_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_request_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('ix_agent_request_status_prio', ['status', 'priority'], unique=False)

    op.create_table('agent_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sdk_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('started', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('last_active', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_session_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_session_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_session_sdk_session_id'), ['sdk_session_id'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('created_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('started_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('finished_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('ix_job_status_kind', ['status', 'kind'], unique=False)

    op.create_table('recipe_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('screenshot_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ts', clipper.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_run_recipe'), ['recipe'], unique=False)

    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proxy_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('heatmap_json', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_hash'), ['hash'], unique=False)

    op.create_table('agenda_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agenda_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agenda_item_scope_id'), ['scope_id'], unique=False)

    op.create_table('agent_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('ts', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_event', schema=None) as batch_op:
        batch_op.create_index('ix_agent_event_session_ts', ['session_id', 'ts'], unique=False)

    op.create_table('analysis',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('transcript_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scenes_json', sa.JSON(), nullable=False),
    sa.Column('energy_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('faces_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signals_json', sa.JSON(), nullable=False),
    sa.Column('created_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('moment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('hook', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payoff', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scores_json', sa.JSON(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moment_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moment_source_id'), ['source_id'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('via', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('timeout_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('answered_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agent_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_session_id'), ['session_id'], unique=False)

    op.create_table('review_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('shipped_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('timeout_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_batch_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('wakeup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agent_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wakeup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wakeup_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wakeup_session_id'), ['session_id'], unique=False)

    op.create_table('clip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moment_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('variant_of', sa.Integer(), nullable=True),
    sa.Column('variant_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preview_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumb_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('layout', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caption_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qa_json', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['moment_id'], ['moment.id'], ),
    sa.ForeignKeyConstraint(['variant_of'], ['clip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clip_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clip_moment_id'), ['moment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clip_status'), ['status'], unique=False)

    op.create_table('edit_op',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('op', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('args_json', sa.JSON(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ts', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edit_op', schema=None) as batch_op:
        batch_op.create_index('ix_edit_op_clip_version', ['clip_id', 'version'], unique=False)

    op.create_table('edl',
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('json', sa.JSON(), nullable=False),
    sa.Column('locked_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], ),
    sa.PrimaryKeyConstraint('clip_id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('posted_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('copy_json', sa.JSON(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], ),
    sa.ForeignKeyConstraint(['platform'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_account_sched', ['account_id', 'scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_clip_id'), ['clip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_status'), ['status'], unique=False)

    op.create_table('review',
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('captions_json', sa.JSON(), nullable=False),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_at', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('via', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score_at_decision', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['review_batch.id'], ),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], ),
    sa.PrimaryKeyConstraint('clip_id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_batch_id'), ['batch_id'], unique=False)

    op.create_table('metric',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('ts', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('earnings', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'ts')
    )
    op.create_table('submission',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', clipper.db.types.UTCDateTime(), nullable=False),
    sa.Column('external_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tracking_ends', clipper.db.types.UTCDateTime(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['marketplace'], ['marketplace.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'campaign_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    op.drop_table('metric')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_batch_id'))

    op.drop_table('review')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_status'))
        batch_op.drop_index(batch_op.f('ix_post_clip_id'))
        batch_op.drop_index(batch_op.f('ix_post_campaign_id'))
        batch_op.drop_index('ix_post_account_sched')

    op.drop_table('post')
    op.drop_table('edl')
    with op.batch_alter_table('edit_op', schema=None) as batch_op:
        batch_op.drop_index('ix_edit_op_clip_version')

    op.drop_table('edit_op')
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_status'))
        batch_op.drop_index(batch_op.f('ix_clip_moment_id'))
        batch_op.drop_index(batch_op.f('ix_clip_campaign_id'))

    op.drop_table('clip')
    with op.batch_alter_table('wakeup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wakeup_session_id'))
        batch_op.drop_index(batch_op.f('ix_wakeup_due_at'))

    op.drop_table('wakeup')
    with op.batch_alter_table('review_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_batch_campaign_id'))

    op.drop_table('review_batch')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_session_id'))

    op.drop_table('question')
    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moment_source_id'))
        batch_op.drop_index(batch_op.f('ix_moment_campaign_id'))

    op.drop_table('moment')
    op.drop_table('analysis')
    with op.batch_alter_table('agent_event', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_event_session_ts')

    op.drop_table('agent_event')
    with op.batch_alter_table('agenda_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agenda_item_scope_id'))

    op.drop_table('agenda_item')
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_hash'))
        batch_op.drop_index(batch_op.f('ix_source_campaign_id'))

    op.drop_table('source')
    with op.batch_alter_table('recipe_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_run_recipe'))

    op.drop_table('recipe_run')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_status_kind')
        batch_op.drop_index(batch_op.f('ix_job_campaign_id'))

    op.drop_table('job')
    with op.batch_alter_table('agent_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_session_sdk_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_session_role'))
        batch_op.drop_index(batch_op.f('ix_agent_session_campaign_id'))

    op.drop_table('agent_session')
    with op.batch_alter_table('agent_request', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_request_status_prio')
        batch_op.drop_index(batch_op.f('ix_agent_request_campaign_id'))

    op.drop_table('agent_request')
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_marketplace'))
        batch_op.drop_index(batch_op.f('ix_campaign_creator'))

    op.drop_table('campaign')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_platform'))

    op.drop_table('account')
    op.drop_table('usage_window')
    op.drop_table('platform')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_scope_id'))

    op.drop_table('note')
    op.drop_table('marketplace')
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_scope'))
        batch_op.drop_index(batch_op.f('ix_lesson_entity_id'))

    op.drop_table('lesson')
    op.drop_table('lease')
    op.drop_table('kv')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('ix_event_type_ts')

    op.drop_table('event')
    op.drop_table('discord_ref')
    # ### end Alembic commands ###
